name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 0 点自动检查（可根据需要调整 cron 表达式）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          ref: main  # 你的默认分支名（如 master/main）

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/liu673cn/box.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git checkout main
          git merge upstream/main --no-edit  # 使用上游分支名

      - name: Push Changes
        run: git push origin main
